"""empty message

Revision ID: a18f01911067
Revises: 
Create Date: 2020-10-20 00:13:12.866471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18f01911067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    cities = op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(cities,
                   [{'id': 1,
                     'city': 'Moscow'},
                    {'id': 2,
                     'city': 'Berlin'},
                    {'id': 3,
                     'city': 'Belgrad'},
                    {'id': 4,
                     'city': 'Tokio'},
                    {'id': 5,
                     'city': 'Oslo'}])
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('cities')
    # ### end Alembic commands ###
